name: Choose
on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'set upload url'
        required: false
        default: '1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;25.0.8775105" --sdk_root=${ANDROID_SDK_ROOT}

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        run: go version

      - name: Set Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init  

      - name: Build
        env:
          BUILD_MOUDLE: app
        run: |
          go mod tidy -v
          gomobile bind -v -androidapi 19 -ldflags='-s -w' ./

      - name: upload apk
        id: apk
        env:
          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
        run: |
          url=${{ github.event.inputs.upload }}
          if [ $url == 1 ]; then
              URL=${UPLOAD_URL}
          else
              URL=${url}
          fi
          BUILD_DATE=`TZ=UTC-8 date '+%Y%m%d_%H%M'`
          
          APK_SOURCE=`find ./ -name "*.aar"`
          APK_NAME=${BUILD_DATE}_xray_.apk
          APK_PATH=`dirname $APK_SOURCE`/$APK_NAME
          mv $APK_SOURCE $APK_PATH
          echo $APK_PATH
          echo $APK_NAME
          echo curl -F scene=default -F output=json2 -F filename=${APK_NAME} -F path=ci  -F file=@./${APK_PATH} ${URL}/group1/upload --insecure
          curl -F scene=default -F output=json2 -F filename=${APK_NAME} -F path=ci  -F file=@./${APK_PATH} ${URL}/group1/upload --insecure
          echo ${URL}/group1/ci/${APK_NAME}

