name: Choose
on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'set upload url'
        required: false
        default: '1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.0
        with:
          cmdline-tools-version: 10406996

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.4.2
        with:
          ndk-version: 'r26b'
          link-to-sdk: true
      - name: Setup Go Mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:~/go/bin

      - name: Build
        run: |
          mkdir -p assets data
          bash gen_assets.sh download
          cp -v data/*.dat assets/
          gomobile init
          go mod tidy
          gomobile bind -v -androidapi 19 -ldflags='-s -w' ./

      - name: upload
        env:
          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
        run: |
          url=${{ github.event.inputs.upload }}
          if [ $url == 1 ]; then
              URL=${UPLOAD_URL}
          else
              URL=${url}
          fi
          BUILD_DATE=`TZ=UTC-8 date '+%Y%m%d_%H%M'`
          APK_SOURCE=`find ./ -name "*.aar"`
          APK_NAME=${BUILD_DATE}_xray_.aar
          APK_PATH=`dirname $APK_SOURCE`/$APK_NAME
          mv $APK_SOURCE $APK_PATH
          echo $APK_PATH
          echo $APK_NAME
          
          echo curl -F scene=default -F output=json2 -F filename=${APK_NAME} -F path=ci  -F file=@./${APK_PATH} ${URL}/group1/upload --insecure
          curl -F scene=default -F output=json2 -F filename=${APK_NAME} -F path=ci  -F file=@./${APK_PATH} ${URL}/group1/upload --insecure
          echo ${URL}/group1/ci/${APK_NAME}

